const ACCOUNT_DATA = [
  { "code": "10", "label": "Capital" },
  { "code": "101", "label": "Capital social" },
  { "code": "1011", "label": "Capital souscrit - non appelé" },
  { "code": "1012", "label": "Capital souscrit - appelé, non versé" },
  { "code": "1013", "label": "Capital souscrit - appelé, versé" },
  { "code": "10131", "label": "Capital non amorti" },
  { "code": "10132", "label": "Capital amorti" },
  { "code": "1018", "label": "Capital souscrit soumis à une réglementation particulière" },
  { "code": "105", "label": "Fonds de dotation" },
  { "code": "108", "label": "Compte de l'exploitant" },
  { "code": "109", "label": "Actionnaires, capital souscrit - non appelé" },
  { "code": "11", "label": "Réserves et primes liées au capital" },
  { "code": "111", "label": "Réserve légale" },
  { "code": "112", "label": "Réserves statutaires" },
  { "code": "117", "label": "Primes liées au capital" },
  { "code": "1171", "label": "Primes d'émission" },
  { "code": "1172", "label": "Primes de fusion" },
  { "code": "1173", "label": "Primes d'apport" },
  { "code": "1174", "label": "Primes de conversion d'obligation" },
  { "code": "1178", "label": "Autres compléments d'apport" },
  { "code": "118", "label": "Autres réserves" },
  { "code": "1181", "label": "Réserves pour fonds social" },
  { "code": "119", "label": "Avoirs des actionnaires" },
  { "code": "12", "label": "Résultats reportés" },
  { "code": "121", "label": "Résultats reportés" },
  { "code": "128", "label": "Modifications comptables affectant les résultats reportés" },
  { "code": "13", "label": "Résultat de l'exercice" },
  { "code": "131", "label": "Résultat bénéficiaire" },
  { "code": "135", "label": "Résultat déficitaire" },
  { "code": "14", "label": "Autres capitaux propres" },
  { "code": "141", "label": "Titres soumis à des réglementations particulières" },
  { "code": "142", "label": "Réserves réglementées & réserves soumises à un régime fiscal particulier" },
  { "code": "1421", "label": "Réserves indisponibles" },
  { "code": "143", "label": "Amortissements dérogatoires" },
  { "code": "144", "label": "Réserve spéciale de réévaluation" },
  { "code": "145", "label": "Subventions d'investissement" },
  { "code": "1451", "label": "Subventions d'investissement" },
  { "code": "1458", "label": "Autres subventions d'investissement" },
  { "code": "1459", "label": "Subventions d'investissement inscrites aux comptes de résultat" },
  { "code": "147", "label": "Compte du concédant" },
  { "code": "15", "label": "Provisions pour risques & charges" },
  { "code": "151", "label": "Provisions pour risques" },
  { "code": "1511", "label": "Provisions pour litiges" },
  { "code": "1512", "label": "Provisions pour garanties données aux clients" },
  { "code": "1513", "label": "Provisions pour pertes sur marchés à achèvement futur" },
  { "code": "1514", "label": "Provisions pour amendes & pénalités" },
  { "code": "1515", "label": "Provisions pour pertes de change" },
  { "code": "1518", "label": "Autres provisions pour risques" },
  { "code": "152", "label": "Provisions pour charges à répartir sur plusieurs exercices" },
  { "code": "1522", "label": "Provisions pour grosses réparations" },
  { "code": "153", "label": "Provisions pour retraites et obligations similaires" },
  { "code": "154", "label": "Provisions d'origine réglementaire" },
  { "code": "155", "label": "Provisions pour impôts" },
  { "code": "156", "label": "Provisions pour renouvellement des immobilisations" },
  { "code": "157", "label": "Provisions pour amortissement" },
  { "code": "158", "label": "Autres provisions pour charges" },
  { "code": "16", "label": "Emprunts & dettes assimilées" },
  { "code": "161", "label": "Emprunts obligataires (assorties de sûretés)" },
  { "code": "1611", "label": "Emprunts obligataires convertibles en actions" },
  { "code": "1618", "label": "Autres emprunts obligataires" },
  { "code": "162", "label": "Emprunts auprès des établissements financiers (assorties de sûretés)" },
  { "code": "1621", "label": "Emprunts bancaires" },
  { "code": "1626", "label": "Refinancements acquis" },
  { "code": "163", "label": "Emprunts auprès d'autres établissements financiers (assorties de sûretés)" },
  { "code": "164", "label": "Emprunts et dettes assorties de conditions particulières" },
  { "code": "1641", "label": "Avances bloquées pour augmentation du capital" },
  { "code": "1642", "label": "Avances reçues et comptes courants des associés bloqués" },
  { "code": "1644", "label": "Avances conditionnées de l'Etat & organismes internationaux" },
  { "code": "165", "label": "Emprunts non assorties de sûretés (à subdiviser selon l'ordre des comptes des emprunts)" },
  { "code": "166", "label": "Dettes rattachées à des participations" },
  { "code": "1661", "label": "Dettes rattachées à des participations (groupe)" },
  { "code": "1662", "label": "Dettes rattachées à des participations (hors groupe)" },
  { "code": "1663", "label": "Dettes rattachées à des sociétés en participation" },
  { "code": "167", "label": "Dépôts & cautionnements reçus" },
  { "code": "168", "label": "Autres emprunts et dettes" },
  { "code": "1681", "label": "Autres emprunts" },
  { "code": "1685", "label": "Crédit fournisseurs d'immobilisations" },
  { "code": "1688", "label": "Autres dettes non courantes" },
  { "code": "17", "label": "Comptes de liaison des établissements & succursales" },
  { "code": "171", "label": "Comptes des liaison des établissements" },
  { "code": "176", "label": "Biens & prestations de services échangés entre établissements (charges)" },
  { "code": "177", "label": "Biens & prestations de services échangés entre établissements (produits)" },
  { "code": "18", "label": "Autres passifs non courants" },
  { "code": "185", "label": "Écarts de conversion" },
  { "code": "188", "label": "Autres" },
  { "code": "21", "label": "Immobilisations incorporelles" },
  { "code": "211", "label": "Investissements de recherche & de développement" },
  { "code": "212", "label": "Concessions de marques, brevets, licences, marques, procédés & valeurs similaires" },
  { "code": "213", "label": "Logiciels" },
  { "code": "214", "label": "Fonds commercial" },
  { "code": "216", "label": "Droit au bail" },
  { "code": "218", "label": "Autres immobilisations incorporelles" },
  { "code": "22", "label": "Immobilisations corporelles" },
  { "code": "221", "label": "Terrains" },
  { "code": "2213", "label": "Terrains nus" },
  { "code": "2214", "label": "Terrains aménagés" },
  { "code": "2215", "label": "Terrains bâtis" },
  { "code": "2216", "label": "Agencements & aménagements des terrains" },
  { "code": "222", "label": "Constructions" },
  { "code": "2221", "label": "Bâtiments" },
  { "code": "2225", "label": "Installations générales, agencements & aménagements des constructions" },
  { "code": "2226", "label": "Ouvrages d'infrastructure" },
  { "code": "2227", "label": "Constructions sur sol d'autrui" },
  { "code": "223", "label": "Installations techniques, matériel et outillage industriels" },
  { "code": "2231", "label": "Installations techniques" },
  { "code": "2234", "label": "Matériel industriel" },
  { "code": "2235", "label": "Outillage industriel" },
  { "code": "2237", "label": "Agencements & aménagements du matériel & outillage industriels" },
  { "code": "224", "label": "Matériel de transport" },
  { "code": "2241", "label": "Matériel de transport de biens" },
  { "code": "2244", "label": "Matériel de transport de personnes" },
  { "code": "228", "label": "Autres immobilisations corporelles" },
  { "code": "2281", "label": "Installations générales, agencements et aménagements divers" },
  { "code": "2282", "label": "Équipement de bureau" },
  { "code": "2286", "label": "Emballages récupérables identifiables" },
  { "code": "23", "label": "Immobilisations en cours" },
  { "code": "231", "label": "Immobilisations incorporelles en cours" },
  { "code": "232", "label": "Immobilisations corporelles en cours" },
  { "code": "237", "label": "Avances & acomptes versés sur immobilisations incorporelles" },
  { "code": "238", "label": "Avances & acomptes versés sur commandes d'immobilisations corporelles" },
  { "code": "24", "label": "Immobilisations à statut juridique particulier" },
  { "code": "25", "label": "Participations & créances liées à des participations" },
  { "code": "251", "label": "Titres de participation" },
  { "code": "2511", "label": "Actions" },
  { "code": "2518", "label": "Autres titres" },
  { "code": "256", "label": "Autres formes de participation" },
  { "code": "257", "label": "Créances rattachées à des participations" },
  { "code": "2571", "label": "Créances rattachées à des participations (groupe)" },
  { "code": "2574", "label": "Créances rattachées à des participations (hors groupe)" },
  { "code": "2575", "label": "Versements représentatifs d'apports non capitalisés (appel de fonds)" },
  { "code": "2576", "label": "Avances consolidables" },
  { "code": "2577", "label": "Autres créances rattachées à des participations" },
  { "code": "258", "label": "Créances rattachées à des sociétés en participation" },
  { "code": "259", "label": "Versements restant à effectuer sur titres de participation non libérés" },
  { "code": "26", "label": "Autres immobilisations financières" },
  { "code": "261", "label": "Titres immobilisés (droit de propriété)" },
  { "code": "2611", "label": "Actions" },
  { "code": "2618", "label": "Autres titres" },
  { "code": "262", "label": "Titres immobilisés (droit de créance)" },
  { "code": "2621", "label": "Obligations" },
  { "code": "2622", "label": "Bons" },
  { "code": "264", "label": "Prêts" },
  { "code": "2641", "label": "Prêts participatifs" },
  { "code": "2642", "label": "Prêts aux associés" },
  { "code": "2643", "label": "Prêts au personnel" },
  { "code": "2645", "label": "Prêts assortis de sûretés (à subdiviser)" },
  { "code": "2648", "label": "Autres prêts" },
  { "code": "265", "label": "Dépôts et cautionnements versés" },
  { "code": "2651", "label": "Dépôts" },
  { "code": "2655", "label": "Cautionnements" },
  { "code": "2656", "label": "Dépôts bancaires non courants" },
  { "code": "2658", "label": "Autres" },
  { "code": "266", "label": "Autres créances immobilisées" },
  { "code": "2661", "label": "Créances immobilisées" },
  { "code": "2667", "label": "Créances diverses" },
  { "code": "2668", "label": "Autres créances non courantes" },
  { "code": "269", "label": "Versements restant à effectuer sur titres immobilisés non libérés" },
  { "code": "27", "label": "Autres actifs non courants" },
  { "code": "271", "label": "Frais préliminaires" },
  { "code": "272", "label": "Charges à répartir" },
  { "code": "273", "label": "Frais d'émission et primes de remboursement des emprunts" },
  { "code": "275", "label": "Écarts de conversion" },
  { "code": "278", "label": "Autres" },
  { "code": "28", "label": "Amortissements des immobilisations" },
  { "code": "281", "label": "Amortissements des immobilisations incorporelles (même ventilation que celle du compte 21)" },
  { "code": "282", "label": "Amortissements des immobilisations corporelles (même ventilation que celle du compte 22)" },
  { "code": "284", "label": "Amortissements des immobilisations à statut juridique particulier" },
  { "code": "29", "label": "Provisions pour dépréciation des immobilisations" },
  { "code": "291", "label": "Provisions pour dépréciation des immobilisations incorporelles (même ventilation que celle du compte 21)" },
  { "code": "292", "label": "Provisions pour dépréciation des immobilisations corporelles (même ventilation que celle du compte 22)" },
  { "code": "293", "label": "Provisions pour dépréciation des immobilisations en cours (même ventilation que celle du compte 23)" },
  { "code": "294", "label": "Provisions pour dépréciation des immobilisations à statut juridique particulier" },
  { "code": "295", "label": "Provisions pour dépréciation des participations et des créances liées à des participations (même ventilation que celle du compte 25)" },
  { "code": "296", "label": "Provisions pour dépréciation des autres immobilisations financières (même ventilation que celle du compte 26)" },
  { "code": "31", "label": "Matières premières & fournitures liées" },
  { "code": "311", "label": "Matières premières" },
  { "code": "313", "label": "Fournitures" },
  { "code": "317", "label": "Autres" },
  { "code": "32", "label": "Autres approvisionnements" },
  { "code": "321", "label": "Matières consommables" },
  { "code": "322", "label": "Fournitures consommables" },
  { "code": "326", "label": "Emballages" },
  { "code": "327", "label": "Autres" },
  { "code": "33", "label": "En-cours de production de biens" },
  { "code": "331", "label": "Produits en cours" },
  { "code": "335", "label": "Travaux en cours" },
  { "code": "34", "label": "En-cours de production de services" },
  { "code": "341", "label": "Études en cours" },
  { "code": "345", "label": "Prestations de services en cours" },
  { "code": "35", "label": "Stocks de produits" },
  { "code": "351", "label": "Produits intermédiaires" },
  { "code": "355", "label": "Produits finis" },
  { "code": "357", "label": "Produits résiduels" },
  { "code": "37", "label": "Stocks de marchandises" },
  { "code": "39", "label": "Provisions pour dépréciation des stocks (à ventiler selon la nomenclature de cette classe)" },
  { "code": "40", "label": "Fournisseurs & comptes rattachés" },
  { "code": "401", "label": "Fournisseurs d'exploitation" },
  { "code": "4011", "label": "Fournisseurs - achats de biens ou de prestations de services" },
  { "code": "4017", "label": "Fournisseurs - retenues de garantie" },
  { "code": "403", "label": "Fournisseurs d'exploitation - effets à payer" },
  { "code": "404", "label": "Fournisseurs d'immobilisations" },
  { "code": "4041", "label": "Fournisseurs - achats d'immobilisations" },
  { "code": "4047", "label": "Fournisseurs d'immobilisations - retenues de garantie" },
  { "code": "405", "label": "Fournisseurs d'immobilisations - effets à payer" },
  { "code": "408", "label": "Fournisseurs - factures non parvenues" },
  { "code": "4081", "label": "Fournisseurs d'exploitation" },
  { "code": "4084", "label": "Fournisseurs d'immobilisations" },
  { "code": "4088", "label": "Fournisseurs - intérêts courus" },
  { "code": "409", "label": "Fournisseurs débiteurs" },
  { "code": "4091", "label": "Fournisseurs - avances et acomptes versés sur commandes" },
  { "code": "4096", "label": "Fournisseurs - créances pour emballages et matériel à rendre" },
  { "code": "4097", "label": "Fournisseurs - autres avoirs" },
  { "code": "40971", "label": "Fournisseurs d'exploitation" },
  { "code": "40974", "label": "Fournisseurs d'immobilisations" },
  { "code": "4098", "label": "Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus" },
  { "code": "41", "label": "Clients & comptes rattachés" },
  { "code": "411", "label": "Clients" },
  { "code": "4111", "label": "Clients - ventes de biens ou de prestations de services" },
  { "code": "4117", "label": "Clients - retenues de garantie" },
  { "code": "413", "label": "Clients - effets à recevoir" },
  { "code": "416", "label": "Clients douteux ou litigieux" },
  { "code": "417", "label": "Créances sur travaux non encore facturables" },
  { "code": "418", "label": "Clients - produits non encore facturés (produits à recevoir)" },
  { "code": "4181", "label": "Factures à établir" },
  { "code": "4188", "label": "Intérêts courus" },
  { "code": "419", "label": "Clients créditeurs" },
  { "code": "4191", "label": "Clients - avances et acomptes reçus sur commandes" },
  { "code": "4196", "label": "Clients - dettes pour emballages et matériel consignés" },
  { "code": "4197", "label": "Clients - autres avoirs" },
  { "code": "4198", "label": "Rabais, remises, ristournes à accorder et autres avoirs à établir" },
  { "code": "42", "label": "Personnel et comptes rattachés" },
  { "code": "421", "label": "Personnel - avances et acomptes" },
  { "code": "422", "label": "Comités d'entreprises et autres organes représentatifs du personnel" },
  { "code": "423", "label": "Personnel, œuvres sociales" },
  { "code": "425", "label": "Personnel - rémunérations dues" },
  { "code": "426", "label": "Personnel - dépôts" },
  { "code": "427", "label": "Personnel - oppositions" },
  { "code": "428", "label": "Personnel - charges à payer & produits à recevoir" },
  { "code": "4282", "label": "Dettes provisionnées pour congés à payer" },
  { "code": "4286", "label": "Autres charges à payer" },
  { "code": "4287", "label": "Produits à recevoir" },
  { "code": "43", "label": "Etat et collectivités publiques" },
  { "code": "431", "label": "Etat - subventions à recevoir" },
  { "code": "432", "label": "Etat, impôts et taxes retenus à la source" },
  { "code": "433", "label": "Opérations particulières avec l'Etat, les collectivités publiques, les organismes internationaux" },
  { "code": "434", "label": "Etat - impôts sur les bénéfices" },
  { "code": "4341", "label": "Retenue à la source" },
  { "code": "4342", "label": "Acomptes provisionnels" },
  { "code": "4343", "label": "Impôt à liquider" },
  { "code": "4349", "label": "Impôts différés" },
  { "code": "435", "label": "Obligations cautionnées" },
  { "code": "436", "label": "Etat - taxes sur le chiffre d'affaires" },
  { "code": "4365", "label": "Taxes sur le chiffre d'affaires à décaisser" },
  { "code": "43651", "label": "TVA à payer" },
  { "code": "43658", "label": "Autres taxes sur le chiffre d'affaires" },
  { "code": "4366", "label": "Taxes sur le chiffre d'affaires déductibles" },
  { "code": "43662", "label": "TVA sur immobilisations" },
  { "code": "43663", "label": "TVA transférée par d'autres entreprises" },
  { "code": "43666", "label": "TVA sur autres biens et services" },
  { "code": "43667", "label": "Crédit de TVA à reporter" },
  { "code": "43668", "label": "Autres taxes sur le chiffre d'affaires" },
  { "code": "4367", "label": "Taxes sur le chiffre d'affaires collectées par l'entreprise" },
  { "code": "43671", "label": "TVA collectée" },
  { "code": "436711", "label": "TVA collectée sur les débits" },
  { "code": "436712", "label": "TVA collectée sur les encaissements" },
  { "code": "43678", "label": "Autres taxes sur le chiffre d'affaires" },
  { "code": "4368", "label": "Taxes sur le chiffre d'affaires à régulariser ou en attente" },
  { "code": "437", "label": "Autres impôts, taxes et versements assimilés" },
  { "code": "438", "label": "Etat - charges à payer et produits à recevoir" },
  { "code": "4382", "label": "Charges fiscales sur congés à payer" },
  { "code": "4386", "label": "Autres charges à payer" },
  { "code": "4387", "label": "Produits à recevoir" },
  { "code": "44", "label": "Sociétés du groupe & associés" },
  { "code": "441", "label": "Groupe" },
  { "code": "4411", "label": "Créances et intérêts courus" },
  { "code": "4412", "label": "Dettes et intérêts à payer" },
  { "code": "442", "label": "Associés - comptes courants" },
  { "code": "4421", "label": "Principal" },
  { "code": "4428", "label": "Intérêts courus" },
  { "code": "446", "label": "Associés - opérations sur le capital" },
  { "code": "447", "label": "Associés - dividendes à payer" },
  { "code": "448", "label": "Associés - opérations faites en commun" },
  { "code": "4481", "label": "Opérations courantes" },
  { "code": "4488", "label": "Intérêts courus" },
  { "code": "45", "label": "Débiteurs divers et Créditeurs divers" },
  { "code": "452", "label": "Créances sur cessions d'immobilisations" },
  { "code": "453", "label": "Sécurité sociale et autres organismes sociaux" },
  { "code": "4531", "label": "Organismes sociaux" },
  { "code": "45311", "label": "CNSS" },
  { "code": "45318", "label": "Autres" },
  { "code": "4538", "label": "Organismes sociaux - charges à payer et produits à recevoir" },
  { "code": "45382", "label": "Charges sociales sur congés à payer" },
  { "code": "45386", "label": "Autres charges à payer" },
  { "code": "45387", "label": "Produits à recevoir" },
  { "code": "454", "label": "Dettes sur acquisitions de valeurs mobilières de placement" },
  { "code": "455", "label": "Créances sur cessions de valeurs mobilières de placement" },
  { "code": "457", "label": "Autres comptes débiteurs ou créditeurs" },
  { "code": "458", "label": "Diverses charges à payer et produits à recevoir" },
  { "code": "4586", "label": "Charges à payer" },
  { "code": "4587", "label": "Produits à recevoir" },
  { "code": "46", "label": "Comptes transitoires ou d'attente" },
  { "code": "461", "label": "Compte d'attente" },
  { "code": "465", "label": "Différence de conversion sur éléments courants" },
  { "code": "4651", "label": "Différences de conversion actif" },
  { "code": "4652", "label": "Différences de conversion passif" },
  { "code": "468", "label": "Autres comptes transitoires" },
  { "code": "47", "label": "Comptes de régularisation" },
  { "code": "471", "label": "Charges constatées d'avance" },
  { "code": "472", "label": "Produits constatés d'avance" },
  { "code": "478", "label": "Comptes de répartition périodique de charges et produits" },
  { "code": "4786", "label": "Charges" },
  { "code": "4787", "label": "Produits" },
  { "code": "48", "label": "Provisions courantes pour risques et charges" },
  { "code": "49", "label": "Provisions pour dépréciation des comptes de tiers" },
  { "code": "491", "label": "Provisions pour dépréciation des comptes clients" },
  { "code": "494", "label": "Provisions pour dépréciation des comptes de groupe et associés" },
  { "code": "4941", "label": "Comptes du groupe" },
  { "code": "4942", "label": "Comptes courants des associés" },
  { "code": "4948", "label": "Opérations faites en commun" },
  { "code": "495", "label": "Provisions pour dépréciation des comptes de débiteurs divers" },
  { "code": "4952", "label": "Créances sur cession d'immobilisation" },
  { "code": "4955", "label": "Créances sur cession des valeurs mobilières de placement" },
  { "code": "4957", "label": "Autres comptes débiteurs" },
  { "code": "50", "label": "Emprunts et autres dettes financières courants" },
  { "code": "501", "label": "Emprunts courants liés au cycle d'exploitation" },
  { "code": "505", "label": "Échéances à moins d'un an sur emprunts non courants" },
  { "code": "506", "label": "Concours bancaires courants" },
  { "code": "5061", "label": "Crédit de mobilisation de créances commerciales" },
  { "code": "5063", "label": "Mobilisation de créances nées à l'étranger" },
  { "code": "5067", "label": "Autres concours bancaires" },
  { "code": "507", "label": "Emprunts échus et impayés" },
  { "code": "508", "label": "Intérêts courus (à subdiviser selon la même ventilation que le compte 50)" },
  { "code": "51", "label": "Prêts et autres créances financières courants" },
  { "code": "511", "label": "Prêts courants liés au cycle d'exploitation" },
  { "code": "516", "label": "Échéances à moins d'un an sur prêts non courants" },
  { "code": "517", "label": "Échéances à moins d'un an sur autres créances financières" },
  { "code": "518", "label": "Intérêts courus" },
  { "code": "52", "label": "Placements courants" },
  { "code": "523", "label": "Actions" },
  { "code": "5231", "label": "Titres cotés" },
  { "code": "5235", "label": "Titres non cotés" },
  { "code": "524", "label": "Autres titres conférant un droit de propriété" },
  { "code": "525", "label": "Obligations et bons émis par la société et rachetés par elle" },
  { "code": "526", "label": "Obligations" },
  { "code": "5261", "label": "Titres cotés" },
  { "code": "5265", "label": "Titres non cotés" },
  { "code": "5266", "label": "Échéances à moins d'un an sur les obligations immobilisées" },
  { "code": "527", "label": "Bons du trésor et bons de caisse à court terme" },
  { "code": "528", "label": "Autres placements courants et créances assimilées" },
  { "code": "5281", "label": "Autres valeurs mobilières" },
  { "code": "5288", "label": "Intérêts courus sur obligations, bons et valeurs assimilées" },
  { "code": "529", "label": "Versements restant à effectuer sur valeurs mobilières de placement non libérées" },
  { "code": "53", "label": "Banques, établissements financiers et assimilés" },
  { "code": "531", "label": "Valeurs à l'encaissement" },
  { "code": "5311", "label": "Coupons échus à l'encaissement" },
  { "code": "5312", "label": "Chèques à encaisser" },
  { "code": "5313", "label": "Effets à l'encaissement" },
  { "code": "5314", "label": "Effets à l'escompte" },
  { "code": "532", "label": "Banques" },
  { "code": "5321", "label": "Comptes en dinars" },
  { "code": "5324", "label": "Comptes en devises" },
  { "code": "534", "label": "C C P" },
  { "code": "535", "label": "Comptes au trésor" },
  { "code": "537", "label": "Autres organismes financiers" },
  { "code": "54", "label": "Caisse" },
  { "code": "541", "label": "Caisse siège social" },
  { "code": "5411", "label": "Caisse en dinars" },
  { "code": "5414", "label": "Caisse en devises" },
  { "code": "542", "label": "Caisses succursales" },
  { "code": "55", "label": "Régies d'avances et accréditifs" },
  { "code": "58", "label": "Virements internes" },
  { "code": "59", "label": "Provisions pour dépréciation des comptes financiers (Même ventilation que les comptes de la classe 5)" },
  { "code": "60", "label": "Achats" },
  { "code": "601", "label": "Achats stockés - Matières premières et fournitures liées" },
  { "code": "602", "label": "Achats stockés - Autres approvisionnements" },
  { "code": "6021", "label": "Matières consommables" },
  { "code": "6022", "label": "Fournitures consommables" },
  { "code": "6026", "label": "Emballages" },
  { "code": "604", "label": "Achats d’études et de prestations de services (y compris achat de sous-traitance de production)" },
  { "code": "605", "label": "Achats de matériel, équipements et travaux" },
  { "code": "606", "label": "Achats non stockés de matières et fournitures" },
  { "code": "607", "label": "Achats de marchandises" },
  { "code": "608", "label": "Achats liés à une modification comptable à prendre en compte dans le résultat de l'exercice ou à une activité abandonnée" },
  { "code": "609", "label": "Rabais, remises et ristournes obtenus sur achats" },
  { "code": "6098", "label": "Liés à une modification comptable à prendre en compte dans le résultat de l'exercice ou à une activité abandonnée" },
  { "code": "61", "label": "Services extérieurs" },
  { "code": "611", "label": "Sous-traitance générale" },
  { "code": "612", "label": "Redevances pour utilisation d'immobilisations concédées" },
  { "code": "613", "label": "Locations (y compris malis sur emballages)" },
  { "code": "614", "label": "Charges locatives et de copropriété" },
  { "code": "615", "label": "Entretien et réparations" },
  { "code": "616", "label": "Primes d'assurances" },
  { "code": "617", "label": "Études, recherches et divers services extérieurs" },
  { "code": "618", "label": "Autres charges liées à une modification comptable à prendre en compte dans le résultat de l'exercice ou à une activité abandonnée" },
  { "code": "619", "label": "Rabais, remises et ristournes obtenus sur services extérieurs" },
  { "code": "62", "label": "Autres services extérieurs" },
  { "code": "621", "label": "Personnel extérieur à l'entreprise" },
  { "code": "622", "label": "Rémunération d'intermédiaires et honoraires" },
  { "code": "623", "label": "Publicité, publications, relations publiques" },
  { "code": "624", "label": "Transports de biens et transports collectifs du personnel" },
  { "code": "6241", "label": "Transports sur achats" },
  { "code": "6242", "label": "Transports sur ventes" },
  { "code": "6244", "label": "Transports administratifs" },
  { "code": "6247", "label": "Transports collectifs du personnel" },
  { "code": "6248", "label": "Divers" },
  { "code": "625", "label": "Déplacements, missions et réceptions" },
  { "code": "6251", "label": "Voyages et déplacements" },
  { "code": "6255", "label": "Frais de déménagement" },
  { "code": "6256", "label": "Missions" },
  { "code": "6257", "label": "Réceptions" },
  { "code": "626", "label": "Frais postaux et frais de télécommunications" },
  { "code": "627", "label": "Services bancaires et assimilés" },
  { "code": "6271", "label": "Frais sur titres (achats, vente, garde)" },
  { "code": "6272", "label": "Commissions et frais sur émission d'emprunts" },
  { "code": "6275", "label": "Frais sur effets" },
  { "code": "6276", "label": "Location de coffres" },
  { "code": "6278", "label": "Autres frais et commissions sur prestations de services" },
  { "code": "628", "label": "Autres services extérieurs liés à une modification comptable à prendre en compte dans le résultat de l'exercice ou à une activité abandonnée" },
  { "code": "629", "label": "Rabais, remises et ristournes obtenus sur autres services extérieurs" },
  { "code": "63", "label": "Charges diverses ordinaires" },
  { "code": "631", "label": "Redevances pour concessions de marques, brevets, licences, procédés, droits et valeurs similaires" },
  { "code": "633", "label": "Jetons de présence" },
  { "code": "634", "label": "Pertes sur créances irrécouvrables" },
  { "code": "6341", "label": "Créances de l'exercice" },
  { "code": "6344", "label": "Créances des exercices antérieurs" },
  { "code": "635", "label": "Quotes-parts de résultat sur opérations faites en commun" },
  { "code": "6351", "label": "Quote-part de bénéfice transférée (comptabilité du gérant)" },
  { "code": "6355", "label": "Quote-part de perte supportée (comptabilité des associés non gérants)" },
  { "code": "636", "label": "Charges nettes sur cessions d'immobilisations et autres pertes sur éléments non récurrents ou exceptionnels" },
  { "code": "637", "label": "Réduction de valeur" },
  { "code": "638", "label": "Charges diverses ordinaires liées à une modification comptable à prendre en compte dans le résultat de l'exercice ou à une activité abandonnée" },
  { "code": "64", "label": "Charges de personnel" },
  { "code": "6401", "label": "Heures supplémentaires" },
  { "code": "6402", "label": "Primes" },
  { "code": "6403", "label": "Gratifications" },
  { "code": "6404", "label": "Avantages en nature" },
  { "code": "6409", "label": "Autres compléments de salaires" },
  { "code": "642", "label": "Appointements et compléments d'appointements" },
  { "code": "6421", "label": "Heures supplémentaires" },
  { "code": "6422", "label": "Primes" },
  { "code": "6423", "label": "Gratifications" },
  { "code": "6424", "label": "Avantages en nature" },
  { "code": "6429", "label": "Autres compléments d'appointements" },
  { "code": "643", "label": "Indemnités représentatives de frais" },
  { "code": "644", "label": "Commissions au personnel" },
  { "code": "6441", "label": "Commissions sur ventes" },
  { "code": "645", "label": "Rémunérations des administrateurs, gérants et associés" },
  { "code": "646", "label": "Charges connexes aux salaires, appointements, commissions et rémunérations" },
  { "code": "64602", "label": "Indemnités de préavis et de licenciements (gratification de fin de service)" },
  { "code": "64604", "label": "Supplément familial" },
  { "code": "64622", "label": "Indemnités de préavis et de licenciement (gratification de fin de service)" },
  { "code": "64624", "label": "Supplément familial" },
  { "code": "64642", "label": "Indemnités de préavis et de licenciement (gratification de fin de service)" },
  { "code": "64644", "label": "Supplément familial" },
  { "code": "64652", "label": "Indemnités de préavis et de licenciement" },
  { "code": "64654", "label": "Supplément familial" },
  { "code": "647", "label": "Charges sociales légales" },
  { "code": "6472", "label": "Cotisations de sécurité sociale sur appointements" },
  { "code": "6474", "label": "Cotisations de sécurité sociale sur commissions" },
  { "code": "6475", "label": "Cotisations de sécurité sociale sur rémunérations des administrateurs et gérants" },
  { "code": "6476", "label": "Prestations directes" },
  { "code": "648", "label": "Charges de personnel liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "649", "label": "Autres charges de personnel et autres charges sociales" },
  { "code": "6495", "label": "Au tres charges sociales" },
  { "code": "65", "label": "Charges financières" },
  { "code": "651", "label": "Charges d'intérêts" },
  { "code": "6511", "label": "Intérêts des emprunts et dettes" },
  { "code": "65116", "label": "Des emprunts et dettes assimilées" },
  { "code": "65117", "label": "Des dettes rattachées à des participations" },
  { "code": "6515", "label": "Intérêts des comptes courants et des dépôts créditeurs" },
  { "code": "6516", "label": "Intérêts bancaires et sur opérations de financement" },
  { "code": "6517", "label": "Intérêts des obligations cautionnées" },
  { "code": "6518", "label": "Intérêts des autres dettes (y compris les pénalités et intérêts de retard sur emprunts)" },
  { "code": "653", "label": "Pertes sur créances liées à des participations" },
  { "code": "654", "label": "Escomptes accordés" },
  { "code": "655", "label": "Pertes de change" },
  { "code": "656", "label": "Charges nettes sur cessions de valeurs mobilières" },
  { "code": "657", "label": "Autres charges financières" },
  { "code": "658", "label": "Charges financières liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "66", "label": "Impôts, taxes et versements assimilés" },
  { "code": "661", "label": "Impôts, taxes et versements assimilés sur rémunérations" },
  { "code": "6611", "label": "TFP" },
  { "code": "6612", "label": "FOPROLOS" },
  { "code": "6618", "label": "Autres" },
  { "code": "665", "label": "Autres impôts, taxes et versements assimilés" },
  { "code": "6651", "label": "Impôts et taxes divers (sauf impôts sur les bénéfices)" },
  { "code": "6652", "label": "Taxes sur le chiffre d'affaires non récupérables" },
  { "code": "6654", "label": "Droits d'enregistrement et de timbre" },
  { "code": "6655", "label": "Taxes sur les véhicules" },
  { "code": "6658", "label": "Autres droits" },
  { "code": "668", "label": "Impôts et taxes liés à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "67", "label": "Pertes extraordinaires" },
  { "code": "68", "label": "Dotations aux amortissements et aux provisions" },
  { "code": "681", "label": "Dotations aux amortissements et aux provisions - charges ordinaires (autres que financières)" },
  { "code": "6811", "label": "Dotations aux amortissements des immobilisations incorporelles et corporelles" },
  { "code": "68111", "label": "Immobilisations incorporelles" },
  { "code": "68112", "label": "Immobilisations corporelles" },
  { "code": "6812", "label": "Dotations aux résorptions des charges reportées" },
  { "code": "6815", "label": "Dotations aux provisions pour risques et charges d'exploitation" },
  { "code": "6816", "label": "Dotations aux provisions pour dépréciation des immobilisations incorporelles et corporelles" },
  { "code": "68161", "label": "Immobilisations incorporelles" },
  { "code": "68162", "label": "Immobilisations corporelles" },
  { "code": "6817", "label": "Dotations aux provisions pour dépréciation des actifs courants (autres que les valeurs mobilières de placement et les équivalents de liquidités)" },
  { "code": "68173", "label": "Stocks et en-cours" },
  { "code": "68174", "label": "Créances" },
  { "code": "6818", "label": "Dotations aux amortissements et aux provisions liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "686", "label": "Dotations aux amortissements et aux provisions - charges financières" },
  { "code": "6861", "label": "Dotations aux amortissements des primes de remboursement des obligations" },
  { "code": "6865", "label": "Dotations aux provisions pour risques et charges financières" },
  { "code": "6866", "label": "Dotations aux provisions pour dépréciation des éléments financiers" },
  { "code": "68662", "label": "Immobilisations financières" },
  { "code": "68665", "label": "Placements et prêts courants" },
  { "code": "6868", "label": "Dotations aux amortissements et aux provisions liées à une modification comptable inscrite dans le résultat de l'exercice ou à une activité abandonnée (charges financières)" },
  { "code": "69", "label": "Impôts sur les bénéfices" },
  { "code": "691", "label": "Impôts sur les bénéfices calculés sur le résultat des activités ordinaires" },
  { "code": "695", "label": "Autres impôts sur les bénéfices (régimes particuliers)" },
  { "code": "697", "label": "Impôts sur les bénéfices calculés sur les éléments extraordinaires" },
  { "code": "70", "label": "Ventes de produits fabriqués, prestations de services, marchandises (A ventiler en ventes aux tiers et ventes aux filiales et entreprises associées, en ventes en dinars et ventes en devises)." },
  { "code": "701", "label": "Ventes de produits finis" },
  { "code": "7011", "label": "Produits finis achevés" },
  { "code": "7012", "label": "Produits finis non achevés (contrat de longue durée)" },
  { "code": "702", "label": "Ventes de produits intermédiaires" },
  { "code": "703", "label": "Ventes de produits résiduels" },
  { "code": "704", "label": "Travaux" },
  { "code": "705", "label": "Études et prestations de services" },
  { "code": "706", "label": "Produits des activités annexes" },
  { "code": "707", "label": "Ventes de marchandises" },
  { "code": "708", "label": "Ventes liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "709", "label": "Rabais, remises et ristournes accordés par l'entreprise" },
  { "code": "7091", "label": "Sur ventes de produits finis" },
  { "code": "7092", "label": "Sur ventes de produits intermédiaires" },
  { "code": "7094", "label": "Sur travaux" },
  { "code": "7095", "label": "Sur études et prestations de services" },
  { "code": "7096", "label": "Sur activités annexes" },
  { "code": "7097", "label": "Sur ventes de marchandises" },
  { "code": "7098", "label": "Sur ventes liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "71", "label": "Production stockée (ou destockage)" },
  { "code": "713", "label": "Variation des stocks (en-cours de production, produits)" },
  { "code": "7133", "label": "Variations des en-cours de production de biens" },
  { "code": "7134", "label": "Variation des en-cours de production de services" },
  { "code": "7135", "label": "Variation des stocks de produits" },
  { "code": "72", "label": "Production immobilisée" },
  { "code": "721", "label": "Immobilisations incorporelles" },
  { "code": "722", "label": "Immobilisations corporelles" },
  { "code": "728", "label": "Production immobilisée liée à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "73", "label": "Produits divers ordinaires" },
  { "code": "731", "label": "Redevances pour concessions, brevets, licences, marques, procédés, droits et valeurs similaires" },
  { "code": "732", "label": "Revenus des immeubles non affectés aux activités professionnelles" },
  { "code": "733", "label": "Jetons de présence et rémunérations d'administrateurs, gérants" },
  { "code": "734", "label": "Ristournes perçues des coopératives (provenant des excédents)" },
  { "code": "735", "label": "Quotes-parts de résultat sur opérations faites en commun" },
  { "code": "736", "label": "Produits nets sur cessions d'immobilisations et autres gains sur éléments non récurrents ou exceptionnels" },
  { "code": "738", "label": "Produits divers ordinaires liés à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "739", "label": "Quotes-parts des subventions d'investissement inscrites au résultat de l'exercice" },
  { "code": "74", "label": "Subventions d'exploitation et d'équilibre" },
  { "code": "741", "label": "Subventions d'exploitation" },
  { "code": "745", "label": "Subventions d'équilibre" },
  { "code": "748", "label": "Subventions liées à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "75", "label": "Produits financiers" },
  { "code": "751", "label": "Produits des participations" },
  { "code": "752", "label": "Produits des autres immobilisations financières" },
  { "code": "753", "label": "Revenus des autres créances" },
  { "code": "754", "label": "Revenus des valeurs mobilières de placement" },
  { "code": "755", "label": "Escomptes obtenus" },
  { "code": "756", "label": "Gains de change" },
  { "code": "757", "label": "Produits nets sur cessions de valeurs mobilières" },
  { "code": "758", "label": "Produits financiers liés à une modification comptable à imputer au résultat de l'exercice ou à une activité abandonnée" },
  { "code": "77", "label": "Gains extraordinaires" },
  { "code": "78", "label": "Reprises sur amortissements et provisions" },
  { "code": "781", "label": "Reprises sur amortissements et provisions (à inscrire dans les produits ordinaires)" },
  { "code": "7811", "label": "Reprises sur amortissements des immobilisations incorporelles et corporelles" },
  { "code": "78111", "label": "Immobilisations incorporelles" },
  { "code": "78112", "label": "Immobilisations corporelles" },
  { "code": "7815", "label": "Reprises sur provisions pour risques et charges d'exploitation" },
  { "code": "7816", "label": "Reprises sur provisions pour dépréciation des immobilisations incorporelles et corporelles" },
  { "code": "78161", "label": "Immobilisations incorporelles" },
  { "code": "78162", "label": "Immobilisations corporelles" },
  { "code": "7817", "label": "Reprises sur provisions pour dépréciation des actifs courants (autres que les valeurs mobilières de placement et les équivalents de liquidités)" },
  { "code": "78173", "label": "Stocks et en-cours" },
  { "code": "78174", "label": "Créances" },
  { "code": "7818", "label": "Reprises sur provisions liées à une modification comptable inscrite aux résultats ou à une activité abandonnée" },
  { "code": "786", "label": "Reprises sur provisions (à inscrire dans les produits financiers)" },
  { "code": "7865", "label": "Reprises sur provisions pour risque et charges financières" },
  { "code": "7866", "label": "Reprises sur provisions pour dépréciation des éléments financiers" },
  { "code": "7868", "label": "Reprises sur provisions (à inscrire dans les produits financiers) liées à une modification comptable inscrite aux résultats de ou à une activité abandonnée" },
  { "code": "79", "label": "Transferts de charges" }
];

const CLASSES = [
  { id: 1, name: "Capitaux propres et passifs non courants", color: "#2563EB" },
  { id: 2, name: "Actifs non courants", color: "#16A34A" },
  { id: 3, name: "Stocks", color: "#EA580C" },
  { id: 4, name: "Tiers", color: "#7C3AED" },
  { id: 5, name: "Comptes financiers", color: "#0D9488" },
  { id: 6, name: "Charges", color: "#DC2626" },
  { id: 7, name: "Produits", color: "#CA8A04" }
];
